@FamilyTreeAPI_HostAddress = https://localhost:7159

GET {{FamilyTreeAPI_HostAddress}}/

###

POST {{FamilyTreeAPI_HostAddress}}/api/createcreator?firstName=Amit&lastname=Dharmkamble

###

GET {{FamilyTreeAPI_HostAddress}}/api/getcreator/7E5D2D5D-2816-48FD-8993-2DEE25E4ACE5

###